from typing import Optional,Dict ,Any
from ..llm_module_generator.image_extraction.image_llm import extract_computational_questions, extract_conceptual_questions
from ..llm_module_generator.ui_generator_static.ui_generator_static import generate_conceputal_html_static,generate_derivation_html_static,generate_lecture_html_static
from ..llm_module_generator.utils import chain, metadata_chain
from ..llm_module_generator.physics_module_generator.module_generator import question_html_generator, question_solution_generator,server_js_generator,server_py_generator,question_html_generator_nonadaptive
from ..logging_config.logging_config import get_logger
from ..llm_module_generator.ui_generator_ai.parser import conceptual_questions_parser,computational_question_parser